version: '3.9'
services:
  scraper_vpn_ch2:
    image: ghcr.io/algo7/tripadvisor-review-scraper/vpn_worker:latest
    deploy:
      # Number of replicas to create
      replicas: 1
      # The restart policy
      restart_policy:
        condition: on-failure
        # Max. number of restart
        max_attempts: 3
      # How the service should be updated => for rolling updates
      update_config:
        # How many containers to update at a time (0 = all at the same time)
        parallelism: 0
        # Delay between updating each container
        delay: 0s
      # Placement options
      placement:
        # User defined constraints
        constraints:
          # Only run on worker nodes
          - 'node.role!=manager'
          - 'node.labels.service==scraper_vpns'
    cap_add:
      - NET_ADMIN
    devices:
      - '/dev/net/tun:/dev/net/tun'
    secrets:
      - source: vpn_credentials.v1
        target: pass.txt
        uid: '0'
        gid: '0'
        mode: 0444
      - source: vpn_config_ch2.v1
        target: config.ovpn
        uid: '0'
        gid: '0'
        mode: 0444
    ports:
      - target: 8888
        published: 8888
        protocol: tcp
      - target: 8881
        published: 8881
        protocol: tcp
      - target: 8881
        published: 8881
        protocol: udp
    networks:
      - vpns

  scraper_vpn_be2:
    image: ghcr.io/algo7/tripadvisor-review-scraper/vpn_worker:latest
    deploy:
      # Number of replicas to create
      replicas: 1
      # The restart policy
      restart_policy:
        condition: on-failure
        # Max. number of restart
        max_attempts: 3
      # How the service should be updated => for rolling updates
      update_config:
        # How many containers to update at a time (0 = all at the same time)
        parallelism: 0
        # Delay between updating each container
        delay: 0s
      # Placement options
      placement:
        # User defined constraints
        constraints:
          # Only run on worker nodes
          - 'node.role!=manager'
          - 'node.labels.service==scraper_vpns'
    cap_add:
      - NET_ADMIN
    devices:
      - '/dev/net/tun:/dev/net/tun'
    secrets:
      - source: vpn_credentials.v1
        target: pass.txt
        uid: '0'
        gid: '0'
        mode: 0444
      - source: vpn_config_be2.v1
        target: config.ovpn
        uid: '0'
        gid: '0'
        mode: 0444
    ports:
      - target: 8888
        published: 8888
        protocol: tcp
      - target: 8881
        published: 8881
        protocol: tcp
      - target: 8881
        published: 8881
        protocol: udp
    networks:
      - vpns

  scraper_vpn_se1:
    image: ghcr.io/algo7/tripadvisor-review-scraper/vpn_worker:latest
    deploy:
      # Number of replicas to create
      replicas: 1
      # The restart policy
      restart_policy:
        condition: on-failure
        # Max. number of restart
        max_attempts: 3
      # How the service should be updated => for rolling updates
      update_config:
        # How many containers to update at a time (0 = all at the same time)
        parallelism: 0
        # Delay between updating each container
        delay: 0s
      # Placement options
      placement:
        # User defined constraints
        constraints:
          # Only run on worker nodes
          - 'node.role!=manager'
          - 'node.labels.service==scraper_vpns'
    cap_add:
      - NET_ADMIN
    devices:
      - '/dev/net/tun:/dev/net/tun'
    secrets:
      - source: vpn_credentials.v1
        target: pass.txt
        uid: '0'
        gid: '0'
        mode: 0444
      - source: vpn_config_se1.v1
        target: config.ovpn
        uid: '0'
        gid: '0'
        mode: 0444
    ports:
      - target: 8888
        published: 8888
        protocol: tcp
      - target: 8881
        published: 8881
        protocol: tcp
      - target: 8881
        published: 8881
        protocol: udp
    networks:
      - vpns

  scraper_vpn_uk13:
    image: ghcr.io/algo7/tripadvisor-review-scraper/vpn_worker:latest
    deploy:
      # Number of replicas to create
      replicas: 1
      # The restart policy
      restart_policy:
        condition: on-failure
        # Max. number of restart
        max_attempts: 3
      # How the service should be updated => for rolling updates
      update_config:
        # How many containers to update at a time (0 = all at the same time)
        parallelism: 0
        # Delay between updating each container
        delay: 0s
      # Placement options
      placement:
        # User defined constraints
        constraints:
          # Only run on worker nodes
          - 'node.role!=manager'
          - 'node.labels.service==scraper_vpns'
    cap_add:
      - NET_ADMIN
    devices:
      - '/dev/net/tun:/dev/net/tun'
    secrets:
      - source: vpn_credentials.v1
        target: pass.txt
        uid: '0'
        gid: '0'
        mode: 0444
      - source: vpn_config_uk13.v1
        target: config.ovpn
        uid: '0'
        gid: '0'
        mode: 0444
    ports:
      - target: 8888
        published: 8888
        protocol: tcp
      - target: 8881
        published: 8881
        protocol: tcp
      - target: 8881
        published: 8881
        protocol: udp
    networks:
      - vpns

networks:
  vpns:
    external: true

# secrets
secrets:
  # Name of the secrets (same as the source)
  vpn_credentials.v1:
    # Use pre-defined secrets created on the manager node
    external: true
  # Name of the secrets (same as the source)
  vpn_config_ch2.v1:
    # Use pre-defined secrets created on the manager node
    external: true
  vpn_config_be2.v1:
    external: true
  vpn_config_se1.v1:
    external: true
  vpn_config_uk13.v1:
    external: true
