version: '3.9'
services:
  vpn:
    image: su:latest
    container_name: vpn
    # Capabilities required to run OpenVPN
    cap_add:
      - NET_ADMIN
    # Devices required to run OpenVPN
    devices:
      - '/dev/net/tun:/dev/net/tun'
    ports:
      # Squid proxy port
      - target: 8888
        published: 8888
        protocol: tcp
      # Dante proxy port
      - target: 8881
        published: 8881
        protocol: tcp
      - target: 8881
        published: 8881
        protocol: udp
    volumes:
      # OpenVPN credentials
      - type: bind
        source: pass.txt
        target: /var/run/secrets/pass.txt

      # OpenVPN configuration
      - type: bind
        source: config.ovpn
        target: /var/run/secrets/config.ovpn
