services:
  scraper:
    environment:
      URL: https://www.tripadvisor.com/Hotel_Review-g1136493-d589283-Reviews-or150-Radisson_RED_Brussels-Ixelles_Brussels.html
    image: ghcr.io/algo7/tripadvisor-review-scraper/scrap:latest
    volumes:
    - source: ./reviews
      target: /puppeteer/data
      type: bind
version: '3.9'

