version: '3.9'
services:
  # Service name
  container_provisioner:
    depends_on:
      - redis
    build: .
    environment:
      IS_CONTAINER: true
      REDIS_HOST: redis:6379
      REDIS_PASS: ''
      R2_URL: https://storage.algo7.tools/
    # Image name
    image: ghcr.io/algo7/tripadvisor-review-scraper/container_provisioner:latest
    volumes:
      # The credentials folder is mounted to the container
      - type: bind
        source: ./credentials
        target: /go/src/app/credentials
        bind:
          create_host_path: true
      # Bind the docker socket to the container so that the provisioner can spin up new containers
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock

    # Map the ports | bind to localhost
    ports:
      # Port in the container
      - target: 3000
        # Port used by the routing mesh
        published: 3000
        protocol: tcp
    # Set up a dedicated network
    networks:
      - container_provisioner

  # Service name
  redis:
    # Image name
    image: redis:alpine
    # Map the ports | bind to localhost
    ports:
      # Port in the container
      - target: 6379
        # Port used by the routing mesh
        published: 6379
        protocol: tcp
    # Set up a dedicated network
    networks:
      - container_provisioner

## Config section
# Define the network type
networks:
  container_provisioner:
    name: container_provisioner
    driver: bridge
    external: false
