name: Build & Push
on:
  push:
    branches:
      - main

# Global variables
env:
  GITHUB_ACTOR: ${{ github.actor }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# Jobs
jobs:
  # Continuous integration
  Build_Scraper:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      # Clone the repo
      - name: Check Out Repo
        uses: actions/checkout@v3

      # Build the image
      - name: Build Image
        run: |
          docker compose build
      # Login to GitHub Container Registry
      - name: Registry Login
        uses: docker/login-action@v2.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: true

      # Push the image to the registry
      - name: Push Image
        run: docker compose push

  # Continuous integration
  Build_Provisioner:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      # Clone the repo
      - name: Check Out Repo
        uses: actions/checkout@v3

      # Build the image
      - name: Build Image
        run: |
          docker compose -f ./container_provisioner/docker-compose-ci.yml build
      # Login to GitHub Container Registry
      - name: Registry Login
        uses: docker/login-action@v2.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: true

      # Push the image to the registry
      - name: Push Image
        run: docker compose -f ./container_provisioner/docker-compose-ci.yml push
